### ISSUE TITLE
Doesn't install to php 8 

### ISSUE THREAD

**Issue by Tautve** [KnpLabs/KnpMarkdownBundle#106]
Hi,

Recently, I've tried to install this package via composer to one of my Symfony projects and I got this problem: "- knplabs/knp-markdown-bundle[1.8.0, ..., 1.8.1] require php ^7.1.3 -> your php version (8.0.0) does not satisfy that requirement.".

I assume the requirement for php 8 has to be upgraded in the package itself? 

I am new to Symfony, so I am not really good at this yet.
![Screen Shot 2020-12-12 at 10 26 16](https://user-images.githubusercontent.com/70275972/101979294-8cb4fe00-3c64-11eb-80f4-6632d7143554.png)

**Comment by Tautve** [comment]
Apparently, I found a way to solve this issue. I've just downloaded another php version (php 7.4) and using brew I linked this version to my system and this solved my problem

**Comment by elkuku** [comment]
oh no... downgrading PHP is not an option - please reopen :(

**Comment by elkuku** [comment]
Has been fixed in #107 :wink:
