### ISSUE TITLE
RFC: Abandon Bundle in favor of Twig's markdown_to_html Filter

### ISSUE THREAD

**Issue by weaverryan** [KnpLabs/KnpMarkdownBundle#116]
I'd like to abandon this bundle. Why? Twig has its own `markdown_to_html` filter: https://twig.symfony.com/doc/3.x/filters/markdown_to_html.html

And, this library even supports the Michelf parser that's used by this bundle. So, migration should be easy.

To make this happen, we would need to:

A) Update the top of the README to clearly state the bundle is abandoned with some nice documentation on how to migrate over to the Twig native version.

B) Mark the package as abandoned in Packagist.

Cheers!

**Comment by bocharsky-bw** [comment]
@weaverryan I suppose the next step will be to make this repo as archived on GitHub to have that little warning above, it would help with discoverability that the bundle is abandoned.
