### ISSUE TITLE
Why are the entities set to "false" by default?

### ISSUE THREAD

**Issue by czechnology** [KnpLabs/KnpMarkdownBundle#20]
The title says it all - why are the entities set to "false" by default in `MarkdownBundle\Parser\MarkdownParser.php`? In my opinion, this behaviour (i.e. entities are escaped instead of displaying) is not compliant with the [syntax documentation](http://daringfireball.net/projects/markdown/syntax#autoescape).

**Comment by akovalyov** [comment]
closed by #67
