### ISSUE TITLE
Can not install

### ISSUE THREAD

**Issue by dutchiexl** [KnpLabs/KnpMarkdownBundle#43]
I get this error on installing with composer 

Problem 1
    - Installation request for symfony/framework-standard-edition 2.2.x-dev -> satisfiable by symfony/framework-standard-edition[2.2.x-dev].
    - symfony/framework-standard-edition 2.2.x-dev requires knplabs/knp-markdown-bundle 1.2.*@dev -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

This is my composer require part:

"require": {
        "php": ">=5.3.3",
        "symfony/symfony": "2.2.*",
        "doctrine/orm": "~2.2,>=2.2.3",
        "doctrine/doctrine-bundle": "1.2.*",
        "twig/extensions": "1.0.*",
        "symfony/assetic-bundle": "2.1.*",
        "symfony/swiftmailer-bundle": "2.2.*",
        "symfony/monolog-bundle": "2.2.*",
        "sensio/distribution-bundle": "2.2.*",
        "sensio/framework-extra-bundle": "2.2.*",
        "sensio/generator-bundle": "2.2.*",
        "jms/security-extra-bundle": "1.4.*",
        "jms/di-extra-bundle": "1.3.*",
        "knplabs/knp-markdown-bundle": "1.2.*@dev",
        "mopa/bootstrap-bundle": "dev-master",
        "twitter/bootstrap": "dev-master",
        "knplabs/knp-paginator-bundle": "dev-master",
        "knplabs/knp-menu": "~2.0@dev",
        "knplabs/knp-menu-bundle": "dev-master",
        "craue/formflow-bundle": "dev-master",
        "friendsofsymfony/user-bundle": "*"
    },

**Comment by akovalyov** [comment]
it is installable.
