### ISSUE TITLE
Please create new release!

### ISSUE THREAD

**Issue by OskarStark** [KnpLabs/KnpMarkdownBundle#66]
to update the depency, which is already fixxed in ```master````

```Package dflydev/markdown is abandoned, you should avoid using it. Use michelf/php-markdown instead.```

Thank you!

**Comment by NiR-** [comment]
@OskarStark Which version of this package have you tried to installed ?
`michelf/php-markdown` is already the library used in the [latest `stable` release](https://github.com/KnpLabs/KnpMarkdownBundle/blob/1.3.2/composer.json#L23).

**Comment by akovalyov** [comment]
@OskarStark please, use ```~1.3``` version. This bundle uses ```michelf/php-markdown``` package since 1.3.0.

**Comment by OskarStark** [comment]
thx @akovalyov

**Comment by akovalyov** [comment]
My pleasure :)
