### ISSUE TITLE
Please tag a new stable version of the bundle

### ISSUE THREAD

**Issue by stof** [KnpLabs/KnpMarkdownBundle#72]
Several changes have been done since the latest release more than 1 year ago. It would be great to great to tag a new version of the bundle.

**Comment by stof** [comment]
note that it would be great to merge the few pending PRs *before* the release rather than after

**Comment by akovalyov** [comment]
@stof done, https://github.com/KnpLabs/KnpMarkdownBundle/releases/tag/1.4. Thank you very much.
