### ISSUE TITLE
markdown 

### ISSUE THREAD

**Issue by GitMostafaoui** [KnpLabs/KnpMarkdownBundle#90]
Hello everyone
i installed knpMarkdown bundle like in the docs with its service
But i got this error:
`ErrorException: Catchable Fatal Error: Argument 1 passed to Knp\Bundle\MarkdownBundle\Twig\Extension\MarkdownTwigExtension::__construct() must be an instance of Knp\Bundle\MarkdownBundle\Parser\ParserManager, none given, called in C:\wamp\www\Hiba\app\cache\dev\appDevDebugProjectContainer.php on line 6468 and defined in C:\wamp\www\Hiba\vendor\knplabs\knp-markdown-bundle\Twig\Extension\MarkdownTwigExtension.php line 11`
can you answer me please what happen?
Thanks a lot.

**Comment by Nek-** [comment]
You tried to manually add the twig extension to the DIC (which is not necessary) and forget its dependency in the configuration.

Just remove your service declaration.

This is not an issue of KnpMarkdownBundle.

**Comment by GitMostafaoui** [comment]
Thanks to much.
