### ISSUE TITLE
`markdown` filter does not escape user HTML tags correctly.

### ISSUE THREAD

**Issue by akester** [KnpLabs/KnpMarkdownBundle#91]
When using the `markdown` twig filter, it does not escape user supplied HTML in the original markdown text.  This then is not escaped by twig's built in escapement function.

As an example, if the user input is `_markdown_ <script>...`, and the filter is used like `{{ var|markdown }}`, the script tag is still outputted into the final HTML.

This can be avoided by first using the stiptags filter (`{{ var|stiptags|markdown }}`), but this may be confusing since the default behavior of the braces is to escape output automatically.

**Comment by eretica** [comment]
I had the same problem, but I solved it by doing like this

{{ var|escape|markdown }}

**Comment by cybernet** [comment]
can this be closed ?

**Comment by weaverryan** [comment]
For now, I think the best we can do is add a note to the README. I've done this based on the suggestions here. Thanks!
